kind: Service
apiVersion: v1
metadata:
  name: bankapp-service
  namespace: bankapp-namespace
  labels:
    app: bankapp
spec:
  selector:
    app: bankapp
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort

