apiVersion: v1
kind: Service
metadata:
  name: node-js-service
  namespace: node-js
spec:
  selector:
    app: node-js-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP


