apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  namespace: node-js
  labels:
    app: node-js-app
spec:
  containers:
  - name: node-js-container
    image: heyitsmeabhishek/nodeapp
    ports:
    - containerPort: 8000

